//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoi_final.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class b_Proizvoditeli
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public b_Proizvoditeli()
        {
            this.b_Zapchasti = new HashSet<b_Zapchasti>();
        }
    
        public int ID_proizvoditela { get; set; }
        public string Nazvanie { get; set; }
        public string Country { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<b_Zapchasti> b_Zapchasti { get; set; }
    }
}
