//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoi_final.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class b_Skladi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public b_Skladi()
        {
            this.b_Zapchasti_na_sklade = new HashSet<b_Zapchasti_na_sklade>();
        }
    
        public int ID_sklada { get; set; }
        public string Nazvanie { get; set; }
        public string Adress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<b_Zapchasti_na_sklade> b_Zapchasti_na_sklade { get; set; }
    }
}
