//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoi_final.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class b_Sotrudniki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public b_Sotrudniki()
        {
            this.b_Tehnicheskoe_obsl = new HashSet<b_Tehnicheskoe_obsl>();
            this.b_Zakazi = new HashSet<b_Zakazi>();
        }
    
        public int ID_sotrudnika { get; set; }
        public string Familia { get; set; }
        public string Name { get; set; }
        public string Otchestvo { get; set; }
        public int ID_role { get; set; }
        public string Dolgnost { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual b_role b_role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<b_Tehnicheskoe_obsl> b_Tehnicheskoe_obsl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<b_Zakazi> b_Zakazi { get; set; }
    }
}
