//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoi_final.Entities
{
    using System;
    using System.Collections.Generic;
    

    public partial class b_Tehnicheskoe_obsl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public b_Tehnicheskoe_obsl()
        {
            this.b_Zapchasti_dla_obslygivania = new HashSet<b_Zapchasti_dla_obslygivania>();
        }
      
            // Другие свойства
            public bool IsOrdered { get; set; }

        public int ID_tehnicheskoe_obsl { get; set; }
        public int ID_samoleta { get; set; }
        public System.DateTime Data_obslygivania { get; set; }
        public int ID_tipa_obslygivania { get; set; }
        public string Opisanie { get; set; }
        public int ID_sotrudnika { get; set; }
    
        public virtual b_Samolet b_Samolet { get; set; }
        public virtual b_Sotrudniki b_Sotrudniki { get; set; }
        public virtual b_Tip_obslygivania b_Tip_obslygivania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<b_Zapchasti_dla_obslygivania> b_Zapchasti_dla_obslygivania { get; set; }
    }
}
