//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoi_final.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class b_Zapchasti_na_sklade
    {
        public int ID_zapchasti_na_sklade { get; set; }
        public int ID_sklada { get; set; }
        public int ID_zapchasti { get; set; }
        public int Kolichestvo { get; set; }
    
        public virtual b_Skladi b_Skladi { get; set; }
        public virtual b_Zapchasti b_Zapchasti { get; set; }
    }
}
