//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoi_final.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class b_Zapchasti_dla_obslygivania
    {
        public int ID_Zapchati_dla_obsl { get; set; }
        public int ID_tehnicheskoe_obsl { get; set; }
        public int ID_zapchasti { get; set; }
    
        public virtual b_Tehnicheskoe_obsl b_Tehnicheskoe_obsl { get; set; }
        public virtual b_Zapchasti b_Zapchasti { get; set; }
    }
}
