//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoi_final.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class b_Zapchasti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public b_Zapchasti()
        {
            this.b_Zakazi = new HashSet<b_Zakazi>();
            this.b_Zapchasti_dla_obslygivania = new HashSet<b_Zapchasti_dla_obslygivania>();
            this.b_Zapchasti_na_sklade = new HashSet<b_Zapchasti_na_sklade>();
        }
        public bool IsSelected { get; set; }
        public int ID_zapchasti { get; set; }
        public string Nazvanie { get; set; }
        public int ID_proizvoditela { get; set; }
        public decimal Cena { get; set; }
    
        public virtual b_Proizvoditeli b_Proizvoditeli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<b_Zakazi> b_Zakazi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<b_Zapchasti_dla_obslygivania> b_Zapchasti_dla_obslygivania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<b_Zapchasti_na_sklade> b_Zapchasti_na_sklade { get; set; }
    }
}
