//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoi_final.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user31_dbEntities : DbContext
    {
        public user31_dbEntities()
            : base("name=user31_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<b_Proizvoditeli> b_Proizvoditeli { get; set; }
        public virtual DbSet<b_role> b_role { get; set; }
        public virtual DbSet<b_Samolet> b_Samolet { get; set; }
        public virtual DbSet<b_Skladi> b_Skladi { get; set; }
        public virtual DbSet<b_Sotrudniki> b_Sotrudniki { get; set; }
        public virtual DbSet<b_Tehnicheskoe_obsl> b_Tehnicheskoe_obsl { get; set; }
        public virtual DbSet<b_Tip_obslygivania> b_Tip_obslygivania { get; set; }
        public virtual DbSet<b_Zakazi> b_Zakazi { get; set; }
        public virtual DbSet<b_Zapchasti> b_Zapchasti { get; set; }
        public virtual DbSet<b_Zapchasti_dla_obslygivania> b_Zapchasti_dla_obslygivania { get; set; }
        public virtual DbSet<b_Zapchasti_na_sklade> b_Zapchasti_na_sklade { get; set; }
    }
}
